# env:
#   browser: true
#   es2021: true
# extends: eslint:recommended
# overrides: []
# parserOptions:
#   ecmaVersion: latest
#   sourceType: module
# rules: {}

---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0